# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9839681fb6207ceaca378cc3138dd88476fc56001544a3d8da3aeef878bbbc7da64bd6e2ed3b63c21c9fecfc083bbfa839e0c5f6235c131f7cfa530c5448b29c

test:
  secret_key_base: 75a9d00762b1eec70cf54cc9b623a0ccc8517666290123602d8a08850aa1e72e62dac403636aba6f6a59551fbffc98c2cf8c4fb068aa461bfd74d1448c69a4f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
